# Generated by Django 4.0.6 on 2022-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='full name')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=75)),
                ('text', models.TextField(verbose_name='your message')),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_answered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
